version: "3.1"
services:
  backend:
    image: eliyahoulevy727/super-app-backend:latest
    build: node
    ports:
      - "3000:3000"
    
  frontend:
    image:  image: eliyahoulevy727/super-app-frontend:latest
    build: php
    ports:
      - "80:80"
    
  db:
    image: mysql:8.0.28   
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'password' 
      MYSQL_DATABASE: 'super-app'

 
    
   
