version: "3.1"
services:
  backend:
    build: node
    ports:
      - "3000:3000"
    image: "eliyahoulevy727/super-app:node"  



 
  frontend:
    build: php
    ports:
      - "80:80"
    image: "eliyahoulevy727/super-app:php"    
    
  db:
    image: mysql:8.0.28
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'password' 
      MYSQL_DATABASE: 'super-app'
     image: "eliyahoulevy727/super-app:db"  
   
