name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:

  build:
    runs-on: ubuntu-latest
 
    steps:
    # need checkout before using compose-action
    - name: checkout code
      uses: actions/checkout@v2
   # - uses: hoverkraft-tech/compose-action@v1.5.1
   #   with:
   #    compose-file: "./docker-compose.yml"

    - name: Build docker
      run: | 
            docker tag super-app-backend eliyahoulevy727/super-app-backend:latest
            docker tag super-app-frontend eliyahoulevy727/super-app-frontend:latest
            docker tag mysql:8.0.28 eliyahoulevy727/super-app-db:latest |
            docker compose up --build
 
 
    - name: get docker images
      run: docker compose config --images
 
    - name: docker push to registry
      run: docker compose push --include-deps
    
    - name: login to docker hub
      run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
  
      
