name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:

  build:
    runs-on: ubuntu-latest
 
    steps:
    # need checkout before using compose-action
    - name: checkout code
      uses: actions/checkout@v2
   # - uses: hoverkraft-tech/compose-action@v1.5.1
   #   with:
   #    compose-file: "./docker-compose.yml"

    - name: Build docker
      run: |
       
         docker compose build 
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: docker up
      run: docker-compose up -f "./docker-compose.yml" -d 
    - name: get docker images
      run: docker compose config --images
    
    - name: change docker tag db
      run:  docker tag mysql:8.0.28 eliyahoulevy727/super-app-db:latest 
    
    - name: change docker tag frontend
      run:  docker tag super-app-frontend eliyahoulevy727/super-app-frontend:latest
    
    - name: change docker tag backend
      run:  docker tag super-app-backend eliyahoulevy727/super-app-backend:latest
 
    - name: get docker images
      run: docker compose config --images
 
    - name: docker push to registry
      run: docker compose push --include-deps
    
    - name: login to docker hub
      run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
  
      
