name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:

  build:

    runs-on: ubuntu-latest
 
    steps:
    # need checkout before using compose-action
    - uses: actions/checkout@v3
    - uses: hoverkraft-tech/compose-action@v1.5.1
      with:
        compose-file: "./docker-compose.yml"

    - name: Build docker
      run: | 
        echo ---Building and starting up docker---
        docker-compose -f ./super-app/docker-compose.yml -p testing up -d
        echo ---Containers up---
   
    - name: login to docker hub
      run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
    
    - name: docker push to registry
      run: docker push eliyahoulevy727/super-app:1
    
