name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: hoverkraft-tech/compose-action@v1.5.1
      with:
        compose-file: "./docker-compose.yml"
        services: |
          frontend
          backend
          db
       
 
    - name: get docker images
      run: docker compose config --images
    
    - name: docker change tag
      run:  docker image tag mysql:8.0.28 eliyahoulevy727/super-app-db:latest   
   
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
   
    - name: docker push to registry
      run: docker compose push 

   

  
      
