name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
 
    steps:

    - name: Install Docker Compose
      run: |
        # Authenticate with Docker Hub
          echo "${DOCKER_PASSWORD}" | docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          checkout
          docker-compose build
          docker tag eliyahoulevy727/super-app:latest eliyahoulevy727/super-app:${{ github.run_naumber }}
          docker push eliyahoulevy727/super-app:${{ github.run_naumber }}
          docker images
   
  





